# Github information
[github]
owner ="synth3xis"
repo ="MyQook_Data-Repository"
token="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"

[edamam]
app_id ="5fd0dac0"
app_key ="334eca2560aea27a4839d48cde7aeb12"
